backend:
  name: github
  repo: dougg0k/eliasjunior_filmes
  branch: master

media_folder: static/assets
public_folder: /assets

# site_url: https://eliasjuniorfilmes.com.br
# logo_url: https://eliasjuniorfilmes.com.br/assets/logo_main.png

locale: "pt"

collections:
  - name: "principaisConteudos"
    label: "Conteudos Principais"
    description: "Conteudos do menu de navegacao, footer e pagina principal"
    create: true
    files:
      - label: "Header"
        name: "header"
        file: "static/content/header/index.md"
        create: true
        fields:
          - { label: "Titulo", name: "title", widget: "string" }
          - { label: "Caminho", name: "path", widget: "string" }
