backend:
  name: github
  repo: dougg0k/eliasjunior_filmes
  branch: master

media_folder: static/assets
public_folder: /assets

# site_url: https://eliasjuniorfilmes.com.br
# logo_url: https://eliasjuniorfilmes.com.br/assets/logo_main.png

locale: "pt"

collections:
  - label: "Header"
    name: "header"
    folder: "static/content/header"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "header",
        }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Caminho", name: "path", widget: "string" }
  - label: "Footer"
    name: "footer"
    folder: "static/content/footer"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "footer",
        }
      - { label: "Texto", name: "text", widget: "string" }
      - { label: "Link", name: "link", widget: "string", required: false }
  - label: "Pagina Principal"
    name: "indexPage"
    folder: "static/content/indexPage"
    create: false
    fields:
      - { label: "Video Link", name: "videoLink", widget: "string" }
  - label: "Filmes"
    name: "filmes"
    folder: "static/content/header"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "header",
        }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Caminho", name: "path", widget: "string" }
