backend:
  name: github
  repo: dougg0k/eliasjunior_filmes
  branch: master

media_folder: static/assets
public_folder: /assets
media_folder_relative: true

site_url: https://eliasjuniorfilmes.com.br
display_url: https://eliasjuniorfilmes.com.br

locale: "pt"

collections:
  - label: "Header"
    name: "header"
    folder: "static/content/header"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "header",
        }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Caminho", name: "path", widget: "string" }
      - {
          label: "Data Cadastro",
          name: "createdAt",
          widget: "datetime",
          format: "DD/MM/YYYY hh:mm:ss",
        }
  - label: "Footer"
    name: "footer"
    folder: "static/content/footer"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "footer",
        }
      - { label: "Texto", name: "text", widget: "string" }
      - { label: "Link URL", name: "url", widget: "string", required: false }
      - {
          label: "Data Cadastro",
          name: "createdAt",
          widget: "datetime",
          format: "DD/MM/YYYY hh:mm:ss",
        }
  - label: "Pagina Principal"
    name: "indexPage"
    folder: "static/content/indexPage"
    create: false
    delete: false
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "indexPage",
        }
      - { label: "Vimeo Link URL", name: "videoUrl", widget: "string" }
  - label: "Filmes"
    name: "filmes"
    folder: "static/content/filmes"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "filmes",
        }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Descricao", name: "description", widget: "text" }
      - { label: "Link URL", name: "url", widget: "string" }
      - {
          label: "Trailer URL",
          name: "trailerUrl",
          widget: "string",
          required: false,
        }
      - {
          label: "Conteudo Gratuito",
          name: "freeContent",
          widget: "boolean",
          default: false,
        }
      - { label: "Capa", name: "cover", widget: "image" }
      - {
          label: "Foto Adicional",
          name: "additionalPicture",
          widget: "image",
          required: false,
        }
      - {
          label: "Data Cadastro",
          name: "createdAt",
          widget: "datetime",
          format: "DD/MM/YYYY hh:mm:ss",
        }
  - label: "Documentarios"
    name: "documentarios"
    folder: "static/content/documentarios"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "documentarios",
        }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Descricao", name: "description", widget: "text" }
      - { label: "Link URL", name: "url", widget: "string" }
      - {
          label: "Trailer URL",
          name: "trailerUrl",
          widget: "string",
          required: false,
        }
      - {
          label: "Conteudo Gratuito",
          name: "freeContent",
          widget: "boolean",
          default: false,
        }
      - { label: "Capa", name: "cover", widget: "image" }
      - {
          label: "Foto Adicional",
          name: "additionalPicture",
          widget: "image",
          required: false,
        }
      - {
          label: "Data Cadastro",
          name: "createdAt",
          widget: "datetime",
          format: "DD/MM/YYYY hh:mm:ss",
        }
  - label: "VideoClipes"
    name: "videoclipes"
    folder: "static/content/videoclipes"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "videoclipes",
        }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Link URL", name: "url", widget: "string" }
      - {
          label: "Conteudo Gratuito",
          name: "freeContent",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Data Cadastro",
          name: "createdAt",
          widget: "datetime",
          format: "DD/MM/YYYY hh:mm:ss",
        }
  - label: "Palestras"
    name: "palestras"
    folder: "static/content/palestras"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "palestras",
        }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Link URL", name: "url", widget: "string" }
      - {
          label: "Descricao",
          name: "descricao",
          widget: "text",
          required: false,
        }
      - {
          label: "Conteudo Gratuito",
          name: "freeContent",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Data Cadastro",
          name: "createdAt",
          widget: "datetime",
          format: "DD/MM/YYYY hh:mm:ss",
        }
  - label: "Entrevistas"
    name: "entrevistas"
    folder: "static/content/entrevistas"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "entrevistas",
        }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Link URL", name: "url", widget: "string" }
      - {
          label: "Conteudo Gratuito",
          name: "freeContent",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Data Cadastro",
          name: "createdAt",
          widget: "datetime",
          format: "DD/MM/YYYY hh:mm:ss",
        }
  - label: "MakingOf"
    name: "makingof"
    folder: "static/content/makingof"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "makingof",
        }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Link URL", name: "url", widget: "string" }
      - {
          label: "Conteudo Gratuito",
          name: "freeContent",
          widget: "boolean",
          default: true,
        }
      - {
          label: "Data Cadastro",
          name: "createdAt",
          widget: "datetime",
          format: "DD/MM/YYYY hh:mm:ss",
        }
  - label: "Cursos"
    name: "cursos"
    folder: "static/content/cursos"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "cursos",
        }
      - { label: "Titulo", name: "title", widget: "string" }
      - { label: "Link URL", name: "url", widget: "string" }
      - {
          label: "Trailer URL",
          name: "trailerUrl",
          widget: "string",
          required: false,
        }
      - {
          label: "Descricao",
          name: "descricao",
          widget: "text",
          required: false,
        }
      - {
          label: "Conteudo Gratuito",
          name: "freeContent",
          widget: "boolean",
          default: false,
        }
      - { label: "Capa", name: "cover", widget: "image" }
      - {
          label: "Data Cadastro",
          name: "createdAt",
          widget: "datetime",
          format: "DD/MM/YYYY hh:mm:ss",
        }
  - label: "Series"
    name: "series"
    folder: "static/content/series"
    create: true
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "series",
        }
      - { label: "Titulo", name: "title", widget: "string" }
      - {
          label: "Conteudo Gratuito",
          name: "freeContent",
          widget: "boolean",
          default: false,
        }
      - {
          label: "Data Cadastro",
          name: "createdAt",
          widget: "datetime",
          format: "DD/MM/YYYY hh:mm:ss",
        }
      - {
          label: "Episodios",
          name: "episodes",
          required: true,
          widget: "list",
          fields:
            [
              {
                label: "Episodio Nº",
                name: "id",
                required: true,
                widget: "number",
                valueType: "int",
              },
              {
                label: "Titulo",
                name: "title",
                required: true,
                widget: "string",
              },
              { label: "Descricao", name: "description", widget: "text" },
              { label: "Link URL", name: "url", widget: "string" },
              {
                label: "Trailer URL",
                name: "trailerUrl",
                widget: "string",
                required: false,
              },
            ],
        }
